#!/usr/bin/env bash

selected_stash=$(git stash list | \
	sk \
		--ansi --no-sort --reverse --tiebreak=index \
		--preview "echo {} | grep -oP '@{\\K\\d+' | xargs -I % sh -c 'git stash show --color=always \'stash@{%}\''" \
		--preview-window=right:70% \
		--bind "alt-j:preview-down,alt-k:preview-up,ctrl-f:preview-page-down,ctrl-b:preview-page-up")

if [ -n "$selected_stash" ]; then
	# Extract the stash number
	stash_number=$(echo "$selected_stash" | grep -oP '@{\K\d+')
	echo "Dropping stash@{$stash_number}..."
	git stash drop "stash@{$stash_number}"
fi
