#!/usr/bin/env bash

set -euo pipefail

git branch \
	--all \
	--color="always" \
	--sort=authordate \
	--format="%(color:blue)%(authordate:relative);%(color:red)%(authorname);%(color:white)%(color:bold)%(refname:short)" \
	"$@" |
	column -s ";" -t
