#!/bin/bash

test_runner="'$*'"

trap "git bisect reset" SIGHUP SIGINT SIGTERM

#First all, write new test untracked by git.
nvim -c 'Vexplore'

git bisect start HEAD $(git fuzzy log)

git bisect run sh -c "eval $test_runner"

git bisect reset
