#!/usr/bin/env bash

selected_stash=$(git stash list | \
	sk \
		--ansi --no-sort --reverse --tiebreak=index \
		--preview "echo {} | sed -n 's/.*@{\([0-9]*\)}.*/\1/p' | xargs -I % sh -c 'git stash show --color=always \'stash@{%}\''" \
		--preview-window=right:70% \
		--bind "alt-j:preview-down,alt-k:preview-up,ctrl-f:preview-page-down,ctrl-b:preview-page-up")

if [ "$selected_stash" != "" ]; then
	# Extract the stash number
	stash_number=$(echo "$selected_stash" | sed -n 's/.*@{\([0-9]*\)}.*/\1/p')
	echo "Popping stash@{$stash_number}..."
	git stash pop "stash@{$stash_number}"
fi
