#!/bin/bash

# Rename the local branch to the new name
git branch -m $1 $2

# Delete the old branch on remote - where <remote> is, for example, origin
git push origin --delete $1

# Or shorter way to delete remote branch [:]
git push origin :$1

# Prevent git from using the old name when pushing in the next step.
# Otherwise, git will use the old upstream name instead of <new_name>.
git branch --unset-upstream $2

# Push the new branch to remote
git push origin $1

# Reset the upstream branch for the new_name local branch
git push origin -u $1
