"alacritty" = ""
"terminal" = ""
"telegram" = ""
"kitty" = ""
"github" = ""
"rust" = ""
"google" = ""
"private browsing" = ""
"firefox" = ""
"chrome" = ""
"file manager" = ""
"nvim" = ""
"gthumb" = ""
"eog" = ""
"transmission" = ""
"mpv" = ""
"music" = ""
".pdf" = "󰈦"
"spotify" = ""
"discord" = "󰙯"
"steam" = ""
"pavucontrol" = "󱡫"
"code" = "󰨞"
"obs" = ""

[other]
deduplicate_icons = true
