require("colors.neon_dream").setup()
require("core.options")
require("core.functions")
require("core.keymaps")
require("core.autocmds")
require("core.lazy")
require("core.lsp")
require("core.statusline")
