hl.on("hyprland.start", function()
	hl.exec_cmd("~/.config/sway/bin/wallpaper.sh")
	hl.exec_cmd("mako")
	hl.exec_cmd("wayle panel start")
	hl.exec_cmd("dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP")
	hl.exec_cmd("hyprsunset")
	hl.exec_cmd("wl-paste --watch cliphist store")
	hl.exec_cmd("~/.config/hypr/bin/xdg-portal.sh")
end)
