[general]
font-sans = "Cascadia Code"
tearing-mode = true

[bar]
scale = 0.6000000238418579
bg = "#1a2642"

[[bar.layout]]
monitor = "*"
show = true
left = ["dashboard"]
center = ["clock"]
right = [
    "media",
    "bluetooth",
    "network",
    "microphone",
    "volume",
    "systray",
]

[styling.palette]
bg = "#1a2642"
surface = "#243556"
elevated = "#2a3d5f"
fg = "#c5d4ff"
fg-muted = "#a8b9e6"
primary = "#5f9eff"
red = "#ff668c"
yellow = "#ffeb99"
green = "#66e8b5"
blue = "#7eb5ff"

[modules.dashboard]
border-show = true
dropdown-lock-command = "hyprlock"

[wallpaper]
engine-enabled = false
cycling-directory = "/home/eryoma/pictures/wallpapers"
cycling-mode = "shuffle"
cycling-interval-mins = 1
cycling-same-image = true
