[general]
font-sans = "Cascadia Code"
tearing-mode = true

[bar]
scale = 0.6000000238418579
bg = "#14161b"
border-color = "transparent"

[[bar.layout]]
monitor = "*"
show = true
left = ["dashboard"]
center = ["clock"]
right = [
    "bluetooth",
    "network",
    "volume",
    "systray",
]

[styling.palette]
bg = "#14161b"
surface = "#2c2e33"
elevated = "#4f5258"
fg = "#eef1f8"
fg-muted = "#e0e2ea"
primary = "#8cf8f7"
red = "#ffc0b9"
yellow = "#fce094"
green = "#b3f6c0"
blue = "#a6dbff"

[modules.dashboard]
border-show = true
dropdown-lock-command = "hyprlock"

[wallpaper]
engine-enabled = false
cycling-directory = "/home/eryoma/pictures/wallpapers"
cycling-mode = "shuffle"
cycling-interval-mins = 1
cycling-same-image = true
