display-name = "Maxim Eryomenko"
downloads-dir = "/home/moeryomenko/downloads/emails"
email-listing-page-size = 100

[rambler]
default = true
email = "maxim_eryomenko@rambler.ru"

backend = "imap"
imap-host = "imap.rambler.ru"
imap-port = 143
imap-login = "maxim_eryomenko@rambler.ru"
imap-starttls = true
imap-passwd-cmd = "pass show moeryomenko/emails/rambler"

sender = "smtp"
smtp-host = "smtp.rambler.ru"
smtp-port = 465
smtp-login = "maxim_eryomenko@rambler.ru"
smtp-starttls = true
smtp-passwd-cmd = "pass show moeryomenko/emails/rambler"
