["Maxim Eryomenko"]
backend = "imap"
email = "maxim_eryomenko@rambler.ru"
default = true
display-name = "Maxim Eryomenko"
imap-host = "imap.rambler.ru"
imap-port = 143
imap-starttls = true
imap-login = "maxim_eryomenko@rambler.ru"
imap-auth = "passwd"
sender = "smtp"
smtp-host = "smtp.rambler.ru"
smtp-port = 587
smtp-starttls = true
smtp-login = "maxim_eryomenko@rambler.ru"
smtp-auth = "passwd"

["Maxim Eryomenko".imap-passwd]
cmd = "pass show eryoma/emails/rambler"

["Maxim Eryomenko".smtp-passwd]
cmd = "pass show eryoma/emails/rambler"

["Maxim Eryomenko".pgp]
backend = "none"
