# vim:filetype=dosini

# hyprsunset configuration
# Profiles activate at their specified time, resetting previous profile settings.

profile {
    time = 06:00
    temperature = 6500
    gamma = 1.0
}

profile {
    time = 18:00
    temperature = 4000
    gamma = 1.0
}
