# vim: ft=swayconfig

# Output configurations
output * {
	bg ~/pictures/wallpapers/forest-river-bridge.jpg fill
	scale 1
	adaptive_sync on
}

# Input configurations
input type:keyboard {
	xkb_layout us,ru
	xkb_options grp:alt_space_toggle
}

input type:touchpad {
    tap            enabled
    dwt            enabled
    natural_scroll enabled
}
