# vim: ft=hyprlang

monitor=DP-1,preferred,0x0,auto
monitor=DP-2,preferred,0x-1440,auto
monitor=HDMI-A-1,1280x720,-1280x0,auto

workspace=1,monitor:DP-1,default:true
workspace=2,monitor:DP-2,default:true
